name: adapt_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Cloud AI & Networking
  google_generative_ai: ^0.4.0
  http: ^1.2.1

  # On-Device ML Kit
  google_mlkit_object_detection: ^0.17.1
  google_mlkit_text_recognition: ^0.17.1
  google_mlkit_image_labeling: ^0.16.1

  # Hardware Sensors & Camera
  camera: ^0.12.0+2
  proximity_sensor: ^1.0.1
  geolocator: ^11.0.0

  # Audio & Feedback Engines
  flutter_tts: ^4.0.2
  speech_to_text: ^7.4.0
  record: ^7.1.1
  vibration: ^3.2.0
  torch_light: ^1.0.0
  shared_preferences: ^2.5.5
  permission_handler: ^11.3.1
  image: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true